name: Pull Request Workflows

on:
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Pull Request Workflows
    steps:
    - name: Assign NEW pull request to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.type == 'PullRequestEvent'
      with:
        project: 'https://github.com/palcarazm/bootstrap5-toggle/projects/2'
        column_name: 'To do'
    - name: Comment in NEW pull request
      uses: peter-evans/create-or-update-comment@v2
      if: github.event.action == 'opened'
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Hi! :wave:
          Thanks for your pull request. You are helping to improve Bootstrap 5 toggle.
        reactions: '+1'
