name: Issues Workflows

on:
  issues:
    types: [opened, milestoned, assigned]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Issues Workflows
    steps:
    - name: Assign NEW issues to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/palcarazm/bootstrap5-toggle/projects/1'
        column_name: 'Needs triage'
    - name: Comment in NEW issues
      uses: peter-evans/create-or-update-comment@v2
      if: github.event.action == 'opened'
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hi! :wave:
          Thanks for your issue. You are helping to improve Bootstrap 5 toggle.
        reactions: '+1'
    - name: High priority issue
      uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
      if: github.event.action == 'milestoned' && github.event.milestone[title] == 'v4.3.0'
      with:
        project: Issue triage
        column: High priority
        repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Low priority issue
      uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
      if: github.event.action == 'milestoned' && github.event.milestone[title] != 'v4.3.0'
      with:
        project: Issue triage
        column: Low priority
        repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: In progress Issue
      uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
      if: github.event.action == 'assigned'
      with:
        project: Issue triage
        column: In progress
        repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
