name: Cypress Tests

on:
  push:
    branches: [ "master", "v3.X.X" ]
  pull_request:
    branches: [ "master", "v3.X.X"  ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
